# Generated by Django 5.0.6 on 2024-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0003_emotion_feeling_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='effect',
            field=models.CharField(default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='negative',
            field=models.CharField(default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='positive',
            field=models.CharField(default='[]', max_length=256),
        ),
    ]
