# Generated by Django 5.0.6 on 2024-08-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrefer', '0002_thoughts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
