# Generated by Django 5.0.6 on 2024-09-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrefer', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_airefer_answer',
            name='answer',
            field=models.CharField(max_length=256),
        ),
    ]
