version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      main:
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn --bind 0.0.0.0:8000 --workers=4 --log-level=debug --capture-output --chdir=/helpfinity_back config.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/helpfinity_back
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      main:

networks:
  main:

volumes:
  postgres_data:
    driver: local
