# Generated by Django 4.1.4 on 2024-03-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('icon', models.ImageField(default='cat_icon/default.png', upload_to='cat_icon')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('cover', models.ImageField(default='podcast_cover/default.png', upload_to='podcast_cover')),
                ('file', models.FileField(upload_to='podcast_file')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.category')),
            ],
        ),
    ]
