# Generated by Django 4.1.4 on 2024-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date_time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='day',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
