# Generated by Django 4.1.4 on 2024-06-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_remove_reminder_date_time_reminder_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
