# Generated by Django 4.1.4 on 2024-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_alter_reminder_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='day',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
